#!/bin/bash

# Mattermost Compliance Export Tools

# Copyright (c) 2023 Maxwell Power
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom
# the Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
# AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

##################################
######### User Settings ##########
##################################

TOKEN=''          ### Your Mattermost PAT
MM_SERVER_URL='' ### Your Mattermost Server URL / With port, if required

##################################

function _usage() {
  printf "Usage: list | latest | date [date(YYY-MM-DD)] | id [ID] \n"
  exit 0
}

function _getReport() {
  ID=$1
  curl -O -s --header "Authorization: Bearer $TOKEN" $MM_SERVER_URL/api/v4/exports/$ID.zip
}

function _getLatestReport() {
  ID=$(curl -s --header "Authorization: Bearer $TOKEN" $MM_SERVER_URL/api/v4/jobs/type/message_export?per_page=1 | jq -r '.[0].id')
  curl -O --header "Authorization: Bearer $TOKEN" $MM_SERVER_URL/api/v4/exports/$ID.zip
}

function _list() {
  curl -s --header "Authorization: Bearer $TOKEN" $MM_SERVER_URL/api/v4/jobs/type/message_export | jq -c '.[]' |
    while IFS=$"\n" read -r c; do
      date=$(echo "$c" | jq -r '.create_at' | cut -c 1-10 | xargs -I {} date -d @{} +"%Y-%m-%d %H:%M")
      id=$(echo "$c" | jq -r '.id')
      messages=$(echo "$c" | jq -r '.data.messages_exported')
      type=$(echo "$c" | jq -r '.data.export_type')
      status=$(echo "$c" | jq -r '.status')
      echo "Date: "$date "ID:" $id "Messages:" $messages "Type:" $type "Status:" $status
    done
}

if [ "$1" == 'list' ]; then
  echo "Getting List of Reports ..."
  _list
elif [ "$1" == 'latest' ]; then
  echo "Getting Latest Report ..."
  _getLatestReport
elif [ "$1" == 'id' ]; then
  echo "Getting Report $2..."
  _getReport $2
else
  _usage
fi
