#!/bin/bash

# List Mattermost User Email Addresses

# Copyright (c) 2023 Maxwell Power
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom
# the Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
# AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

##################################
######### User Settings ##########
##################################


TOKEN=''          ### Your Mattermost PAT
MM_SERVER_URL='' ### Your Mattermost Server URL (including port, if required). Example https://mattermost.example.com:8065

##################################

function _list() {
  curl -s --header "Authorization: Bearer $TOKEN" $MM_SERVER_URL/api/v4/users?per_page=200 | jq -c '.[]' |
    while IFS=$"\n" read -r c; do
      email=$(echo "$c" | jq -r '.email')
      echo $email
    done
}

_list
